import { Manrope } from "next/font/google";
import "./globals.css";
import Loader from "@/components/Loader/Loader";
import ErrorModal from "@/components/ErrorModal/ErrorModal";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Онлайн тренер",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className} >
      <Loader/>
      <ErrorModal/>
      {children}
      </body>
    </html>
  );
}
